### ISSUE TITLE
drawChild这个函数不是应该一屏能画几个就调几次么

### ISSUE THREAD

**Issue by TedWithAHammer** [YiChaoLove/CoverFlow#1]
调试了下 本身想改一下 只需要中间那个变大 其他可以正常大小 发现drawChild函数调了多几次（就是头尾加的那些） 导致我z轴偏移有点问题 我是直接设了一个固定值 只要是最中间那个项

**Comment by YiChaoLove** [comment]
多次的调用（包括在adapter中添加头尾隐藏的item）并不会对计算  Camera的Z轴偏移量  产生影响，如果只需要中间item变大，那么适当的更改mCamera.translate(x, y, z)中z值即可。
理论上来说RecyclerView应该会绘制比当前屏幕数多的item。
